FurniAppTemplate/Areas/Admin/ViewModels/Furniture/FurnitureCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace FurniAppTemplate.Areas.Admin.ViewModels.Furniture
{
    public class FurnitureCreateVM
    {
        public string Title { get; set; }
        public int Price { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public IFormFile Photo { get; set; }
    }
}

FurniAppTemplate/Areas/Admin/ViewModels/Furniture/FurnitureUpdateVM.cs
namespace FurniAppTemplate.Areas.Admin.ViewModels.Furniture
{
    public class FurnitureUpdateVM
    {
        public string Title { get; set; }
        public int Price { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public IFormFile Photo { get; set; }
    }
}

FurniAppTemplate/Models/Furniture.cs
namespace FurniAppTemplate.Models
{
    public class Furniture:BaseEntity
    {
        public string Title { get; set; }
        public int Price { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
    }
}

FurniAppTemplate/Areas/Admin/Controllers/FurnitureController.cs
using FurniAppTemplate.Areas.Admin.ViewModels.Furniture;
using FurniAppTemplate.Data;
using FurniAppTemplate.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace FurniAppTemplate.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FurnitureController : Controller
    {
        public FurnitureDbContext _furnitureDbContext;

        public FurnitureController(FurnitureDbContext furnitureDbContext)
        {
            _furnitureDbContext = furnitureDbContext;
        }
        public IActionResult Index()
        {
            var furnitures=_furnitureDbContext.Furnitures.ToList();
            return View(furnitures);
        }
        public IActionResult Detail(int? id)
        {
            if (id is null) return BadRequest();

            var furniture = _furnitureDbContext.Furnitures.FirstOrDefault(f => f.Id == id);
            if (furniture is null) return NotFound();

            return View(furniture);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task< IActionResult > Create(FurnitureCreateVM furniture)
        {
            var file = furniture.Photo;
            if (file==null)
            {
                ModelState.AddModelError("Photo", "bos ola bilmez");
                return View(furniture);
            }
            string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);
            using FileStream fileStream = new(path, FileMode.Create);
            await file.CopyToAsync(fileStream);
            var newFurniture = new Furniture()
            {
                Title = furniture.Title,
                Price=furniture.Price,
                ImageURL = fileName,
                Description =furniture.Description
            };
            await _furnitureDbContext.Furnitures.AddAsync(newFurniture);
            await _furnitureDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return BadRequest();

            var furniture = _furnitureDbContext.Furnitures.FirstOrDefault(f => f.Id == id);
            if (furniture is null) return NotFound();
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", furniture.ImageURL);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            _furnitureDbContext.Furnitures.Remove(furniture);
            await _furnitureDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int? id)
        {
            if(id is null) return BadRequest();
            var furniture =await _furnitureDbContext.Furnitures.FirstOrDefaultAsync(f => f.Id == id);
            if (furniture is null) return NotFound();
            return View(new FurnitureUpdateVM { Description=furniture.Description,Title=furniture.Title,Price=furniture.Price,ImageURL=furniture.ImageURL});
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id,FurnitureUpdateVM furnitureUpdateVM)
        {
            if (id is null) return BadRequest();
            var furniture = await _furnitureDbContext.Furnitures.FirstOrDefaultAsync(f => f.Id == id);
            if (furniture is null) return NotFound();
            var file = furnitureUpdateVM.Photo;
            if (file == null)
            {
                ModelState.AddModelError("Photo", "Şəkil boş ola bilməz");
                furnitureUpdateVM.ImageURL = furniture.ImageURL;
                return View(furnitureUpdateVM);
            }
            string oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", furniture.ImageURL);
            if (System.IO.File.Exists(oldPath))
            {
                System.IO.File.Delete(oldPath);
            }
            string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
            string newPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);
            using (FileStream stream = new FileStream(newPath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            furniture.ImageURL = fileName;
            furniture.Price = furnitureUpdateVM.Price;
            furniture.Description = furnitureUpdateVM.Description;
            furniture.Title = furnitureUpdateVM.Title;
            await _furnitureDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

FurniAppTemplate/Areas/Admin/Views/Furniture/Create.cshtml
@model FurnitureCreateVM
<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Furniture Create form</h4>
                <form enctype="multipart/form-data" asp-area="Admin" asp-controller="Furniture" asp-action="Create" class="forms-sample" method="post">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input asp-for="Photo" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description"class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price"></label>
                        <input asp-for="Price" class="form-control" placeholder="Price">
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>
                    <button type="submit" class="btn btn-primary me-2">Create</button>
                    <a asp-area="Admin" asp-controller="Furniture" asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-3gJwYpA0rjPJoPqlHHz7E+YPLZC1U+G9v0Fkl6f3FHvgnkEcMNFVXyWkZww7k5FDLU7LgR35MxLsEE+w5z+J3w=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"
            integrity="sha512-rstlgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWlEV/PP+Tr04hbtA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"
            integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3lhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}

FurniAppTemplate/Areas/Admin/Views/Furniture/Detail.cshtml
@model Furniture

<div class="container mt-4">
    <h2>Furniture Detail</h2>

    <div class="card p-4">
        <div class="row">
            <div class="col-md-6">
                <img src="~/images/@Model.ImageURL" class="img-fluid rounded shadow" />
            </div>
            <div class="col-md-6">
                <h4>@Model.Title</h4>
                <p><strong>Description:</strong> @Model.Description</p>
                <p><strong>Price:</strong> $@Model.Price</p>
                <a asp-action="Index" class="btn btn-secondary mt-3">Back to List</a>
            </div>
        </div>
    </div>
</div>

FurniAppTemplate/Areas/Admin/Views/Furniture/Index.cshtml
@model IEnumerable<Furniture>

<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Category Table</h4>
                    <a class="btn btn-outline-success" asp-area="admin" asp-controller="furniture" asp-action="create">Create</a>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Price</th>
                                    <th>Image</th>
                                    <th>Settings</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var furniture in Model)
                                {
                                    <tr>
                                        <td>@furniture.Title</td>
                                        <td>@furniture.Description</td>
                                        <td>@furniture.Price</td>
                                        <td>
                                            <img src="~/images/@furniture.ImageURL" />
                                        </td>
                                        <td>
                                            <a class="btn btn-outline-primary" asp-action="detail" asp-route-id="@furniture.Id">Detail</a>
                                            <a class="btn btn-outline-success" asp-action="update" asp-route-id="@furniture.Id">Update</a>
                                            <a class="btn btn-outline-danger" asp-action="delete" asp-route-id="@furniture.Id">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FurniAppTemplate/Areas/Admin/Views/Furniture/Update.cshtml
@model FurnitureUpdateVM
<div class="container">
    <div class="row">
        <div class="card">
            <img src="~/images/@Model.ImageURL" width="500" height="100" />
            <div class="card-body">
                <h4 class="card-title">Slider Update form</h4>

                <form enctype="multipart/form-data" asp-action="update" class="forms-sample" method="post">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price"></label>
                        <input asp-for="Price" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input asp-for="Photo" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>

                    <button type="submit" class="btn btn-primary me-2">Update</button>
                    <a asp-action="index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>